# Generated by Django 4.1.6 on 2023-02-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='copies_sold',
            field=models.IntegerField(default=0),
        ),
    ]
