# Generated by Django 4.1.6 on 2023-02-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='refunded',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
